### ISSUE TITLE
No Atmos in Outpost's Chemistry

### ISSUE THREAD

**Issue by AzzyIsNotHere** [NTCanadaTeam/NTCanada#12]
## Round ID:
29

## Reproduction: 
Outpost's Chemistry has no atmos due to airless tiles. Nuff said.

**Comment by unit0016** [comment]
oh boy, and I was just committing a new update. something similar may have happened to the gateway? investigating.

**Comment by unit0016** [comment]
Commit 3290a26c525203b7d68133dc67244c102e1b7380 fixes. Closing issue.
