### ISSUE TITLE
Auto-update not working with TGS4, leading to deployments several PRs behind

### ISSUE THREAD

**Issue by AzzyIsNotHere** [NTCanadaTeam/NTCanada#9]
As title says. I am assigning myself to this issue, and I have created said issue to document the problem and potential solution for the future.
Ignore the lack of template.

**Comment by unit0016** [comment]
oh boy, again?

**Comment by AzzyIsNotHere** [comment]
Fixed. TGS had several issues, mainly with the Watchdog, which led to updates no longer working. Server will be updated to TGS 4.3.2 when it is released.
